// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
    
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4I1uexNSoG61XBaOz0KERiYaCW4XuYW0',
    appId: '1:1067730549731:web:c7f2174906427e30afbed6',
    messagingSenderId: '1067730549731',
    projectId: 'fittymobile-2edfa',
    authDomain: 'fittymobile-2edfa.firebaseapp.com',
    storageBucket: 'fittymobile-2edfa.appspot.com',
    measurementId: 'G-KQ3S3E577V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB19kAYMy60F24UEJ4aeNNRGKE2YOyhFto',
    appId: '1:1067730549731:android:27c539c48af387d7afbed6',
    messagingSenderId: '1067730549731',
    projectId: 'fittymobile-2edfa',
    storageBucket: 'fittymobile-2edfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6qPcKZCf3dXrDDqfCi9zzSzuZBnzi4E',
    appId: '1:1067730549731:ios:e8b89c0978eb847bafbed6',
    messagingSenderId: '1067730549731',
    projectId: 'fittymobile-2edfa',
    storageBucket: 'fittymobile-2edfa.appspot.com',
    iosBundleId: 'com.example.fitty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6qPcKZCf3dXrDDqfCi9zzSzuZBnzi4E',
    appId: '1:1067730549731:ios:e8b89c0978eb847bafbed6',
    messagingSenderId: '1067730549731',
    projectId: 'fittymobile-2edfa',
    storageBucket: 'fittymobile-2edfa.appspot.com',
    iosBundleId: 'com.example.fitty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4I1uexNSoG61XBaOz0KERiYaCW4XuYW0',
    appId: '1:1067730549731:web:5cdc8ebf0460d919afbed6',
    messagingSenderId: '1067730549731',
    projectId: 'fittymobile-2edfa',
    authDomain: 'fittymobile-2edfa.firebaseapp.com',
    storageBucket: 'fittymobile-2edfa.appspot.com',
    measurementId: 'G-Q2BHT9CKRV',
  );

}